baseURL = "https://d194cqm3knl40v.cloudfront.net/" # CloudFront adresin
languageCode = "tr"
title = "Muhammed Asef"
theme = "blowfish"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[params]
  colorScheme = "blowfish"
  defaultTheme = "dark"
  enableSearch = true

  # Ana Sayfa Ayarları
  [params.homepage]
    layout = "background"
    showRecent = true
    showRecentItems = 3
    [params.homepage.button]
      enable = true
      text = "Projelerime Git"
      url = "projects/"

  # Yazar Ayarları (Sorun çıkaran kısım düzeltildi)
  [params.author]
    name = "Muhammed Asef"
    image = "images/profil-foto.jpg"
    # Daktilo efekti burada:
    headline = """<div class="typewriter"><h1>DevOps Engineer & Cloud Enthusiast</h1></div>"""
    bio = "Otomasyon, Cloud Native teknolojiler ve CI/CD süreçleri üzerine çalışıyorum."
    
    # Sosyal Linkler
    links = [
      { email = "mailto:asefkmv4@gmail.com" },
      { github = "https://github.com/MuhammedAsef" },
      { linkedin = "https://linkedin.com/in/muhammedasefkumandaveren013" }
    ]

  [params.header]
    layout = "fixed"

  [params.footer]
    showScrollToTop = true

# HTML kodlarının çalışması için güvenlik izni
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projeler"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Hakkımda"
    url = "/about/"
    weight = 20