baseURL = "https://d194cqm3knl40v.cloudfront.net/" # CloudFront adresin
languageCode = "tr"
title = "Muhammed Asef"
theme = "blowfish"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[params]
  colorScheme = "blowfish" # Veya "fireball", "horizon" gibi renkleri var
  defaultTheme = "dark"
  
  # Ana Sayfa (Hero) Ayarları - Senin istediğin o havalı giriş
  [params.homepage]
    layout = "background" # Arka planda görsel olsun
    showRecent = true
    showRecentItems = 3
    
    [params.homepage.button]
      enable = true
      text = "Projelerime Git"
      url = "projects/"

  # Üst Kısım (Header)
  [params.header]
    layout = "fixed"

  # Alt Kısım (Footer)
  [params.footer]
    showScrollToTop = true

  # Yazar Bilgisi (Sol üstte veya Hero'da çıkar)
  [author]
    name = "Muhammed Asef"
    image = "images/profil-foto.jpg" # Profil foton buraya
    headline = """<div class="typewriter"><h1>DevOps Engineer & Cloud Enthusiast</h1></div>"""
    bio = "Otomasyon, Cloud Native teknolojiler ve CI/CD süreçleri üzerine çalışıyorum."
    links = [
      { email = "mailto:asefkmv4@gmail.com" },
      { github = "https://github.com/MuhammedAsef" },
      { linkedin = "https://linkedin.com/in/muhammedasefkumandaveren013" }
    ]

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projeler"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Hakkımda"
    url = "/about/"
    weight = 20
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true