baseURL = "https://d194cqm3knl40v.cloudfront.net/" # Ä°leride gerÃ§ek domaininle deÄŸiÅŸtireceÄŸiz
languageCode = "tr"
title = "My DevOps Journey" # Buraya kendi adÄ±nÄ± da yazabilirsin
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[params]
    defaultTheme = "dark" # DevOps ruhuna uygun olarak varsayÄ±lan karanlÄ±k mod
    description = "Cloud, Automation, and DevOps Portfolio"
    author = "Muhammed Asef Kumandaveren"
    
    # Ana sayfada gÃ¶rÃ¼necek profil kÄ±smÄ±
    [params.homeInfoParams]
        # Title = "Merhaba, Ben Muhammed Asef Kumandaveren ğŸ‘‹"
        Title = """<div class="typewriter"><h1>Merhaba, Ben Muhammed Asef KumandaverenğŸ‘‹</h1></div>"""
        Content = """
        DevOps MÃ¼hendisiyi AdayÄ±yÄ±m.
        Otomasyon, Cloud Native teknolojiler ve CI/CD sÃ¼reÃ§leri Ã¼zerine Ã§alÄ±ÅŸÄ±yorum.
        ğŸš€ Bu site AWS Ã¼zerinde barÄ±nmakta ve GitHub Actions ile otomatik deploy edilmektedir.
        """

    # Sosyal Medya Ä°konlarÄ± (Linkleri kendine gÃ¶re dÃ¼zenle)
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/MuhammedAsef"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/muhammedasefkumandaveren013"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:asefkmv4@gmail.com"

[menu]
    [[menu.main]]
        identifier = "projects"
        name = "Projeler"
        url = "/projects/"
        weight = 10
    [[menu.main]]
        identifier = "about"
        name = "HakkÄ±mda"
        url = "/about/"
        weight = 20
    [[menu.main]]
        identifier = "archives"
        name = "ArÅŸiv"
        url = "/archives/"
        weight = 30
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true